#+title:                 sweep NEWS -- history of user-visible changes.
#+author:                Eshel Yaron
#+email:                 me@eshelyaron.com
#+language:              en
#+options:               ':t toc:nil num:nil ^:{}
#+startup:               content indent
#+MACRO: version (eval (mapconcat #'number-to-string (save-current-buffer (with-current-buffer (find-file (expand-file-name "sweep.el" (file-name-directory $1))) (package-desc-version (package-buffer-info)))) "."))

This file is about changes in =sweep= up to version
{{{version({{{input-file}}})}}}.

* New commands available in =sweep= {{{version({{{input-file}}})}}}

** New command =sweep-load-buffer=.

Loads a =sweep-mode= buffer.  If called from a =sweep-mode= buffer, loads
the current buffer by default.

** New command =sweep-find-file-at-point=.

Follows file specifications in =sweep-mode= buffers.


* New keybindings in =sweep-mode= buffers

** =C-c C-l= is now bound to =sweep-load-buffer=.

** =C-c C-o= is now bound to =sweep-find-file-at-point=.


* New user options available in =sweep= {{{version({{{input-file}}})}}}

** New user option =sweep-colourise-buffer-on-idle=

This option is a boolean flag that determines whether to enable
automatic updating of semantic highlighting in =sweep-mode= buffers.

** New user option =sweep-colourise-buffer-min-interval=

This option determines the minimum number of idle seconds that =sweep=
will wait before updating semantic highlighting in a =sweep-mode=
buffer.

** New user option =sweep-colourise-buffer-max-size=

This option determines the maximum size of a =sweep-mode= buffer for
which =sweep= will periodically update semantic highlighting on idle.

** New user option =sweep-top-level-min-history-length=

This option, set by default to 3, determines a minimum length for
inputs inserted into =sweep= top-level history ring.  The default value,
3, avoids one character top-level responses from clobbering the
history ring.  This kind of inputs includes, for example, the =;=
character typed to invoke backtracking.

* New keybindings in =sweep-prefix-map=

** The =l= key is now bound to =sweep-load-buffer=.
